---
 # This will automatically launch EC2 instance, install nginx, flask, etc...
 # Pull application repo and deploy it
  - name: Bring up an EC2 instance
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    vars_files:
      - vars/main.yml
      - /vars/keys.yml
    tasks:
      - name: Launch new EC2 instance
        local_action:
          module: ec2
          instance_tags: "Name={{ server_name }}"
          group: "{{ security_group }}"
          instance_type: "{{ instance_type}}"
          image: "{{ image }}"
          wait: true
          region: "{{ region }}"
          keypair: "{{ keypair }}"
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
        register: ec2
      - name: Add the new instance to host group
        local_action: add_host hostname={{ item.public_ip }} groupname=launched
        with_items: ec2.instances
      - name: Wait till SSH come up
        local_action: wait_for host={{ item.public_dns_name }} port=22 delay=120 timeout=320 state=started
        with_items: ec2.instances

  - name: Install the requirements and deploy application on the above instance
    hosts: launched
    vars_files:
      - vars/main.yml
    sudo: yes
    remote_user: "{{ sys_user }}"
    gather_facts: True
    roles:
      - init
      - nginx-install
      - venv
      - app-repo
      - nginx-conf
      - uwsgi
